[package]
name = "ripper-convert"
description = "Converters from Unity objects to SekaiStoryRipper output formats"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
crc32fast.workspace = true
cridecoder.workspace = true
png.workspace = true
ripper-format.workspace = true
ripper-unity.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
